### PR TITLE
date and pcre extensions are always present in PHP

### PR DESCRIPTION
**Pull request by vbashkirtsev**
Removed them from composer.json

### CODE REVIEW

**Comment by hayate** [comment]
LGTM :bow:

**Comment by hayate** [comment]
@vbashkirtsev I am working to finally merge this PR to master however I am having issues with `composer install`
image

seems that the `logics/sql` package cannot be downloaded, do you have any suggestions?

**Comment by vbashkirtsev** [comment]
You don't have Subversion client installed on your system. Composer uses it to access repositories.

**Comment by hayate** [comment]
@vbashkirtsev thank you for quick reply.

**Comment by vbashkirtsev** [comment]
You're welcome :)

**Pull request closed without merging**
