### PR TITLE
Upgraded to PHPUnit 5.7

### PR DESCRIPTION
**Pull request by vbashkirtsev**
PHPUnit now has new best practice for exception testing: instead of @expectedException annotation in docblock use of $this->expectException() and relevant methods is preferred, This allows to specify the point in the test where exception is expected instead of blanket exception expectation.

Also replaced @requiredconst annotation with @internalconst annotation since GENGO_PUBKEY and GENGO_PRIVKEY constants are not configurable and used solely in tests.

Please merge and bump version to 3.0.2

### CODE REVIEW

**Comment by hayate** [comment]
Thank you for you update @vbashkirtsev do you think you could:
1. update the change log
2. fix the php coding standard failures (https://travis-ci.org/gengo/gengo-php/builds/196023444)

**Comment by vbashkirtsev** [comment]
Will add couple of lines to change log. Hang on.

**Comment by vbashkirtsev** [comment]
Now all looks good :)

**Comment by hayate** [comment]
Thank you @vbashkirtsev do you mind updating the user-agent as well please?
https://github.com/gengo/gengo-php/blob/master/src/Client.php#L177

**Comment by vbashkirtsev** [comment]
Done :)

**Pull request merged**
