### PR TITLE
Gengo PHP API 3.0.0

### PR DESCRIPTION
**Pull request by vbashkirtsev**
As promised: here's brand new Gengo PHP API. When I started to add namespaces and PSR-4 I've got carried away :) So pretty much all PHP API was rewritten.

Your standard of LGTM is not high enough for me: I'd rather rely on 100% test coverage. So of course this new API comes with full test suite.

I also note that while I was making tests I found that Gengo server in some instances returns 500 errors: something really hairy on Gengo server side. I hope these issues are on sandbox system only and production server will not fail in this way. I guess you should check it out.

And finally: why Gengo as a company would not hire someone to make such sort of work instead of relying on a goodwill of end users? I thought it is beneficial to Gengo and its business.

### CODE REVIEW

**Comment by hayate** [comment]
@vbashkirtsev thank you for your PR.

**The next steps are:**
* I will checkout your branch and carefully review your code
* Our QA team will run regression tests 

In the mean time, could you fix the conflicts so that the branch can eventually be merged?

**Comment by hayate** [comment]
@vbashkirtsev please see my feedback below.
Most of my comments are related to style. Please let me know if you can work on any of the below issues. If you cannot work on any of the below issues then please just take care of point `8` and `9` below.


1. All constant strings should be single quotes not double quotes (PHP parses every double quoted string to find possible variable substitution i.e. in the case of "job_{$i}" php will replace {$i} with its value, 'job_{$i}' is ignored because is is in single quotes. Single quotes are more efficient.
2. Remove php closing tag (`?>`) it is not required. see: http://php.net/basic-syntax.instruction-separation
3. Remove underscore for `private/protected` methods. Underscore was introduced when php did not have accessors (i.e. `public/protected/public`) before version 5, currently they are not required anymore.
4. Files have a combination of tabs and spaces. It is normally better to stick with one or the other. At Gengo we use 4 spaces for indentation and NEVER tabs.
5. Add `setBaseURL` to `Config.php` class (We need to be able to set different base url, i.e. staging, dev environment etc)
6. Could you make the two methods in `ApproveRejectValidator` decorators? i.e.:
    ```php
    function decorator($method, array $params)
    {
        if (!array_key_exists('foo', $params)) {
            print("foo must bar\n");
        } else {
            print("all is good, running the method!\n");
            $method($params);
        }
    }

    function actual(array $params)
    {
        decorator(function() use ($params) {
            print('foo is: '.$params['foo']."\n");
        }, $params);
    }

    $params = ['foo' => 'bar'];
    actual($params);
    ```
7. Remove empty line between method and comment
8. Please fix merge conflicts 
9. Please make this PR against the `version-3.0` branch instead of master and close this PR.

**Comment by vbashkirtsev** [comment]
Originally there were no apparent coding style standard used so I used what we use as matter of convenience.

Style requirements are actually enforced by CodeSniffer which is one of require-dev in composer.json . You can run it from vendor/bin/phpcs . The standard we use is Beauty and it enforces:
1. Double quote preferred to single quotes. They are actually have the same performance as single quotes: they have the same opcode. See https://nikic.github.io/2012/01/09/Disproving-the-Single-Quotes-Performance-Myth.html
2. Closing tag is enforced as well as spacing around it. Closing tag in php is optional and in our view counterbalancing open things is a good practice in general.
3. Underscores in private methods and properties: it is just a convention. This allows to quickly ascertain if the method called is private without reverting to original method definition.
4. Tabs/spaces and tab size: it is just a matter of preference. There's number of reasons why we use combination of tabs and spaces: historical, size-wise, performance, visualization in environments we use.
7. Blank line between methods and comments: again just a convention enforced by CodeSniffer (one line before method name, two before docblock).

We all come from different backgrounds and tastes. In our company we require all the code to pass CodeSniffer check before code is accepted to repository. While we prefer all the code we have to follow Beauty standard requirements may be adjusted by re-configuring CodeSniffer. The only requirement is to have CodeSniffer to succeed.

I personally see no problem of running this code through some sort of reformatter if you wish but would prefer not to do it as our builder will complain loudly. (BTW there's ant's build.xml which we use to build the project in our Jenkins)

Point 5: I did not know that you have number of end-points: in API docs only two are mentioned. I thought to limit user's ability to use only known end-points and so they are hard coded. I guess useProduction() may have optional $baseURL parameter to allow custom end-points to be used. May be rename useProduction() into something more apparent for such use in this case.

On other hand setting custom URL should be used by Gengo internal operations only. End-user should have no interest to point it anywhere else but sandbox or production Gengo servers. (unless they implemented their own Gengo server :) Therefore the question: does end-user really need such flexibility? In my view answer is no.

Point 6: Originally ApproveRejectValidator appeared as common functionality between classes Job and Jobs.  These validators are not user serviceable components as validation rules are dictated by Gengo. Therefore I don't see a good use case for a decorators. Did I miss something in my reasoning?

Point 8: I guess it is because of your last commit. I have pulled down the repo just before it. Will get it fixed.

Point 9: Certainly

**Comment by hayate** [comment]
@vbashkirtsev thank you for doing points 8 and 9. Points 1-7  will become our (Gengo) TODO list before merging to master.

**Pull request closed without merging**
