### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by hayate**
This is a complete rewrite that uses php namespaces rather than snake case class names.
The rewrite is not compatible with the previous version hence the bump to version 3.0 from 2.1.7.

Currently version 2.1.7 and version 3 support the same Gengo api functionality.

### CODE REVIEW

**Comment by hayate** [comment]
@vbashkirtsev [http://open.logics.net.au/](http://open.logics.net.au/) seems to be down... 
`logics/sql` fails to download on travis (which should have subversion by default)
If that is the case, I hope it does not happen often...

**Comment by vbashkirtsev** [comment]
We were unlucky to have 19 hours of blackout yesterday :( Our DC run out of batteries! But generally it does not happen very often - last time it was two or three years ago caused by a truck running into power pole.

On other hand we consider to move our open source stuff onto GitHub: for better availability and community involvement.

**Comment by hayate** [comment]
@vbashkirtsev got it thank you!

**Comment by vbashkirtsev** [comment]
Congrats! Let's see how it will work! We will get it connected back to our project through composer during the week and hopefully it will be OK.

**Comment by vbashkirtsev** [comment]
Please kick Packagist.org if it is not on auto-update. Otherwise it may take up to one week to update.

**Comment by vbashkirtsev** [comment]
Please disregard last message: it is already there :)

**Comment by vbashkirtsev** [comment]
I have modified our project to use Gengo API 3.0 and now can report that migration was pretty much painless. I removed references to former init, added three lines for config of public key, private key and useProduction(), replaced calls to Factory with new Jobs(), new Job() and new Order() and that's it. As I tried to keep original method names and relevant signatures intact all uses of API remained the same with exception of that there now no need for separate call to fetch response - now calls to API are one-liners instead of two.

So all in all I am happy with the way it integrates: now it is up to wider community to judge.

PS: please accept latest PR with last minute fixes and push it Packagist as 3.0.1

**Pull request merged**
