### PR TITLE
Fixed the job PUT parameter for_mygengo

### PR DESCRIPTION
**Pull request by DawnAngel**
As described in the API documentation, now for_gengo -> for_mygengo

http://developers.gengo.com/v2/api_methods/job/index.html?highlight=for_mygengo#job-put

### CODE REVIEW

**Comment by hermanschaaf** [comment]
Good catch! For legacy reasons, `for_mygengo` does indeed seem to be the correct name. We could probably update our code to also accept `for_gengo`, but it's better to keep the library in sync with the docs for now. LGTM :+1:

**Comment by DawnAngel** [comment]
I've also noticed that the "rating" parameter for the same job (PUT) is not working and it's strange because the API documentation is saying that is correct.

I've tested for several values and no value was stored.

"rating" => "5" // not working
"rating" => "4.0" // not working
"rating" => 4 // not working

PD: Could you please check this as well? Thanks!

**Comment by hayate** [comment]
LGTM

thank you Eric, added a bug ticket to our bug tracker for the rating issue.

**Comment by hermanschaaf** [comment]
@DawnAngel I had a look on our side: `"rating" => 4` is the correct format (i.e. it needs to be an integer, but I'm making the system more forgiving now, to also allow floats and strings).

I suspect some of the confusion is perhaps from the fact that after you call `PUT` with the `accept` parameter on a job, the rating and feedback gets saved to our database, and displayed on the site, but does not get returned with subsequent `GET` requests to the job. This is unfortunately a limitation with the current version of our API, and not quite what one would expect, and we should probably make a note of that in the docs. 

Does that clear things up somewhat? Let me know if you're still stuck, and thanks again for this PR!

**Comment by hermanschaaf** [comment]
Oh, but I forgot to mention that you could use the `GET feedback` endpoint: http://developers.gengo.com/v2/api_methods/job/#id6 - is that what you have tried, and it's not showing up?

**Comment by hermanschaaf** [comment]
Actually I just tried that myself and it's showing `0.0` for me too - ignore the above if you were in fact using the `GET feedback` endpoint already :smile:

**Comment by DawnAngel** [comment]
I meant that `0.0`indeed, thanks for researching!

I look forward for the your next release then ;)

**Comment by hermanschaaf** [comment]
@DawnAngel We looked into the rating issue and fixed the problem on our side. Feedback should be returning non-zero ratings for your case now. Can you maybe try again and let me know how it goes?

I will also merge your PR now and add a new tag, thanks again!

**Pull request merged**
